### ISSUE TITLE
colcon build is failing on this package

### ISSUE THREAD

**Issue by arekin19** [cmrobotics/cmr_geometry_utils#4]
I run the playbook on Serena-4 to update the stack. I have this error, maybe the playbook is missing some packages?

Starting >>> micro_ros_msgs
--- stderr: cmr_geometry_utils                                   
CMake Error at /home/ros/workspace/cmr_ros_ws/install/cmr_tests_utils/share/cmr_tests_utils/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package):
  By not providing "Findcmr_clients_utils.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "cmr_clients_utils", but CMake did not find one.

  Could not find a package configuration file provided by "cmr_clients_utils"
  with any of the following names:

    cmr_clients_utilsConfig.cmake
    cmr_clients_utils-config.cmake

  Add the installation prefix of "cmr_clients_utils" to CMAKE_PREFIX_PATH or
  set "cmr_clients_utils_DIR" to a directory containing one of the above
  files.  If "cmr_clients_utils" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  /home/ros/workspace/cmr_ros_ws/install/cmr_tests_utils/share/cmr_tests_utils/cmake/cmr_tests_utilsConfig.cmake:41 (include)
  test/CMakeLists.txt:8 (find_package)

---
Failed   <<< cmr_geometry_utils [1.61s, exited with code 1]

**Comment by arekin19** [comment]
All packages are in the playbook: geometry, test and clients. I tried colcon build for individual packages (cmr_tests, clients and geometry). Tests and clients are built successfully, only geometry is failing.

**Comment by arekin19** [comment]
@guilyx could you take a look on this?

**Comment by guilyx** [comment]
Is your playbook running on latest master branch? I know Axel had that error but wasn't running it on latest

**Comment by guilyx** [comment]
Try again,close if it works @arekin19

**Comment by arekin19** [comment]
Tested, working. I'm closing :)
